### ISSUE TITLE
The problem about training!

### ISSUE THREAD

**Issue by mei123hao** [hlwang1124/SNE-RoadSeg#11]
Hello !! I try to run the training program . My GPU card is NVIDIA GTX1080 with 8GB memory. But it always reports cuda out of memory when run the training program .  I try to low down the batch size to 1. But it still report error like this:
RuntimeError: CUDA out of memory. Tried to allocate 118.00 MiB (GPU 0; 7.92 GiB total capacity; 6.24 GiB already allocated; 139.69 MiB free; 304.82 MiB cached)
I try to run the program in a larger memory card, which has 11GB memory. It can start training successfully. But after running several epoch it always make the computer restart. What's wrong with that? Please help! THANKS !

**Comment by hlwang1124** [comment]
Hi, mei123hao. Sorry for the late response, and hope you have already solved this problem. Maybe you can revise this line for a smaller network. https://github.com/hlwang1124/SNE-RoadSeg/blob/5e15ef16642b6b425c4074e025a1704312d06240/models/networks.py#L108

**Comment by hlwang1124** [comment]
An inactive issue closed.
