### ISSUE TITLE
Can I ask why the result of SNE can predict more lanes as compared with provided gt

### ISSUE THREAD

**Issue by Cli98** [hlwang1124/SNE-RoadSeg#14]
Hi @hlwang1124 ,

Congratulations for your paper acceptance! I'm a newbie in road segmentation and for now I want to ask some questions regarding your freespace segmentation.

Check the following two plots,

![um_000028](https://user-images.githubusercontent.com/19630616/98195744-78a51080-1ef0-11eb-8562-605e9db4b6c9.png)

![um_000028](https://user-images.githubusercontent.com/19630616/98195757-7f338800-1ef0-11eb-9bb1-2b82e1a5fd6b.png)

Compare those two plots, The ground truth (below one) has only one lane labeled, while your prediction (above one) can label two lanes. This is impressive. Can you tell me how this works? As I assume that you have knowledge for only one lane (Namely gt one). Then how is SNE able to generalize to inference both lanes?

Thank you if you can leave me some hints.

**Comment by hlwang1124** [comment]
Hi, @Cli98. It seems that this image is `um_000028.png` in `image_2`, and the corresponding ground truth `um_road_000028.png` in `gt_image_2` has two lanes labeled, shown as follows.
![um_road_000028](https://user-images.githubusercontent.com/25403947/98198042-0b7e9300-1f63-11eb-8dce-7fc309558e8f.png)

**Comment by Cli98** [comment]
> Hi, @Cli98. It seems that this image is `um_000028.png` in `image_2`, and the corresponding ground truth `um_road_000028.png` in `gt_image_2` has two lanes labeled, shown as follows.
> ![um_road_000028](https://user-images.githubusercontent.com/25403947/98198042-0b7e9300-1f63-11eb-8dce-7fc309558e8f.png)


Please allow me to say "thank you" to you. I did not pay enough attention to data and will focus more on those annotations. Thank you for your kindly response and I wish you stay safe.
