### ISSUE TITLE
I wonder if you use any pretrain weight to train SNE-RoadSeg

### ISSUE THREAD

**Issue by Cli98** [hlwang1124/SNE-RoadSeg#15]
Hi @hlwang1124 ,

Would you mind me to ask if you have used any pretrain weights to train this model? For example, use imagenet as the pretrain weight for the backbone or etc.

Thank you if you can provide me with some insights.

Wish you a great day,

**Comment by hlwang1124** [comment]
Hi, we use the pre-trained weight provided in `torchvision`. It is pre-trained on ImageNet.

**Comment by Cli98** [comment]
Thank you @hlwang1124 . I highly appreciate you help.
