### ISSUE TITLE
I wonder if you use Lambda L1 loss to train you model

### ISSUE THREAD

**Issue by Cli98** [hlwang1124/SNE-RoadSeg#16]
Hi @hlwang1124 ,

I just checked your source code. And I have one question. You defined a variable called "Lambda L1 loss" in parser. But I am not able to find what you apply it. Can you tell me if you use it to train your model?

Thank you,

**Comment by hlwang1124** [comment]
Hi, @Cli98 . We do not use it. It is from the original [pytorch-CycleGAN-and-pix2pix](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix).

**Comment by Cli98** [comment]
> Hi, @Cli98 . We do not use it. It is from the original [pytorch-CycleGAN-and-pix2pix](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix).

Good to hear from you and thank you for letting me know this.
