### ISSUE TITLE
depth_u16 download problem 

### ISSUE THREAD

**Issue by JiayiLy** [hlwang1124/SNE-RoadSeg#18]
Hi, the link you give for downloading depth_u16 is inaccessable. 
Can you please give another address ? Thank you so much.

**Comment by hlwang1124** [comment]
Hi, @JiayiLy .
Sorry that the previous link is invalid. Please download `depth_u16` from this [new link](https://drive.google.com/file/d/16ft3_V8bMM-av5khZpP6_-Vtz-kF6X7c/view?usp=sharing).
