### ISSUE TITLE
R2D dataset issue

### ISSUE THREAD

**Issue by SimonSongg** [hlwang1124/SNE-RoadSeg#21]
Hi,

I tried to download the R2D dataset and to train. But the labels of this dataset seem to be all in black. And the depth images have many strange texture. Should it be like this? Thank you very much.
![000000](https://user-images.githubusercontent.com/70959938/109271239-365e6100-784a-11eb-8d65-65f1ae78e1b3.png)
![image](https://user-images.githubusercontent.com/70959938/109271272-41b18c80-784a-11eb-930f-844b530da946.png)

**Comment by hlwang1124** [comment]
Hi, @SimonSongg . Our R2D dataset is collected in the Carla simulation environment. Please refer to [this link](https://carla.readthedocs.io/en/stable/cameras_and_sensors/) for the data format of depth maps and semantic segmentation maps.

**Comment by SimonSongg** [comment]
> Hi, @SimonSongg . Our R2D dataset is collected in the Carla simulation environment. Please refer to [this link](https://carla.readthedocs.io/en/stable/cameras_and_sensors/) for the data format of depth maps and semantic segmentation maps.

Thank you very much!!! Sorry for the stupid question ☹.

**Comment by SimonSongg** [comment]
> Hi, @SimonSongg . Our R2D dataset is collected in the Carla simulation environment. Please refer to [this link](https://carla.readthedocs.io/en/stable/cameras_and_sensors/) for the data format of depth maps and semantic segmentation maps.
Hi, @hlwang1124 . I just tried to train by the kitti dataset with resnet 18. And it had an error after an epoch. 

(epoch: 1, iters: 290, time: 0.115, data: 0.068) segmentation: 0.463
End of epoch 1 / 1000    Time Taken: 119 sec
learning rate = 0.0010000
Traceback (most recent call last):
  File "train.py", line 119, in <module>
    avg_valid_loss = torch.mean(torch.stack(valid_loss_iter))
RuntimeError: expected a non-empty list of Tensors

Could you help to fix it? Thanks!!!

**Comment by SimonSongg** [comment]
> Hi, @SimonSongg . Our R2D dataset is collected in the Carla simulation environment. Please refer to [this link](https://carla.readthedocs.io/en/stable/cameras_and_sensors/) for the data format of depth maps and semantic segmentation maps.

I comment lines
```python
119: avg_valid_loss = torch.mean(torch.stack(valid_loss_iter))
123: writer.add_scalar('valid/loss', avg_valid_loss, epoch)
```
in train.py and I can train without any error.

**Comment by hlwang1124** [comment]
It seems that you did not split a validation set.

**Comment by SimonSongg** [comment]
> It seems that you did not split a validation set.

sorry for the stupid mistake!!!!!!!! I forgot it. Thank you for your patience.

**Comment by hlwang1124** [comment]
It's OK. Happy to see that everything works now:)

**Comment by wxyWendy** [comment]
Excuse me,I haved referred to https://carla.readthedocs.io/en/stable/cameras_and_sensors/ for the data format of depth maps and semantic segmentation maps,but I still don't how can I convert the depth images and the labels.Could you please You can tell me the specific conversion operation？Thank you very much!!!!
