### ISSUE TITLE
problem getting the road-segmented image from a single rgb image

### ISSUE THREAD

**Issue by bpfrd** [hlwang1124/SNE-RoadSeg#23]
Hello
My input is a single rgb image and I would like to get its road-segmented image. But I still have some problems running the code. 
It seems to in addition to the input image, it also needs depth-image. I was wondering what depth-image is? How can I generate it for my input rgb image?
I am running the following script. the path "datasets/kitti/testing" contains my input image only.
python3 test.py --dataroot datasets/kitti --dataset kitti --name kitti --use_sne --prob_map --no_label --epoch kitti
I really appreciate it if you can help. 
Best regards
Behnam

**Comment by hlwang1124** [comment]
Hi. Our approach is a data-fusion one that requires RGB images and the corresponding depth images as input. Many road datasets such as KITTI and Cityscape provide these kinds of data. If you are using your own dataset that does not contain depth images, I suggest you either 1) use other single-modal networks (e.g., DeepLabv3+) or 2) first use monocular depth estimation approaches to generate the depth images and then use our data-fusion network.
