### ISSUE TITLE
Problem of producing normal from  a depth image

### ISSUE THREAD

**Issue by RobbyHuang** [hlwang1124/SNE-RoadSeg#28]
Tanks for your sharing!

I try to use the SNE module to produce a normal image from a depth, but It seems that the quality of the result is not good. 
The depth image I used is from the YCB_Video.
![000001-depth](https://user-images.githubusercontent.com/41146244/113642902-7d463e80-96b3-11eb-98b5-b47765f16234.png)

![000001-normal](https://user-images.githubusercontent.com/41146244/113642885-728ba980-96b3-11eb-8953-266d0a942ebc.png)

```
depth_image = cv2.imread(depth_path, cv2.IMREAD_ANYDEPTH)
sne_model = SNE() 
camParam = torch.tensor([[1.066778e+03, 0.000000e+00, 3.129869e+02],
                                           [0.000000e+00, 1.067487e+03, 2.413109e+02],
                                           [0.000000e+00, 0.000000e+00, 1.000000e+00]], dtype=torch.float32)  # camera parameters
normal = sne_model(torch.tensor(depth_image.astype(np.float32)/1000), camParam)
normal_image = normal.cpu().numpy()
normal_image = np.transpose(normal_image, [1, 2, 0])
cv2.imwrite(normal_path, cv2.cvtColor(255 * (1 + normal_image) / 2, cv2.COLOR_RGB2BGR))

```

Could you give me some advice?Thanks!

**Comment by hlwang1124** [comment]
Hi, @RobbyHuang .
I think this is due to the invalid pixels in the depth image. A possible solution is to refine the depth image.

**Comment by RobbyHuang** [comment]
Hi,@hlwang1124 Thanks for your reply.
Have you tried to use the SNE module to convert the depth image produced by the camera to normal?
I found the same problem, when I convert the depth image produced by intel Realsense D435i to normal.
Have you tried to refine the depth image？ Can you recommend some related algorithms？
Thanks！

**Comment by hlwang1124** [comment]
Yes, I tried using the SNE module to convert Intel RealSense depth images to the corresponding surface normal, as shown [here](https://github.com/hlwang1124/NIM). Although there also exist invalid pixels, I found that they have little influence on the drivable area and road anomaly detection. Therefore, I have not tried to refine the depth image.
