### ISSUE TITLE
How to generate dense depth images from lidar point cloud?

### ISSUE THREAD

**Issue by mei123hao** [hlwang1124/SNE-RoadSeg#29]
Hello Wang:
@hlwang1124 I found that the generated dense depth image may influence the inference performance. Can you provide the dense depth image generation code for us? I try your method mentioned in [#7](https://github.com/hlwang1124/SNE-RoadSeg/issues/7). But it seems that generated result is different from your privided depth_u16 data. My EMAIL: yue_zhuang@qq.com. Thanks a lot!

**Comment by hlwang1124** [comment]
Hi, @mei123hao . I will organize the code and send it to you.

**Comment by mei123hao** [comment]
> Hi, @mei123hao . I will organize the code and send it to you.

Thanks a lot !

**Comment by mei123hao** [comment]
> Hi, @mei123hao . I will organize the code and send it to you.

Hi Wang:
Have you sent the code to me? I still don't receive it?

**Comment by hlwang1124** [comment]
Sorry that I am busy with other projects. I will send the code to you before the next weekend. Thanks for your understanding.

**Comment by mei123hao** [comment]
Hi Wang：
I am sorry to bother you again!! Have you sent me the code? It has past three weeks, I still don't receive your code?

**Comment by hlwang1124** [comment]
Hi, @mei123hao . So sorry for the late response. I have sent the code to your email. Thanks for your understanding.

**Comment by mei123hao** [comment]
> Hi, @mei123hao . So sorry for the late response. I have sent the code to your email. Thanks for your understanding.

Thank you very much!

**Comment by DaniloXiao** [comment]
Can you share the script generously，thanks.

**Comment by DaniloXiao** [comment]
> > Hi, @mei123hao . So sorry for the late response. I have sent the code to your email. Thanks for your understanding.
> 
> Thank you very much!

Can you share the script generously，thanks.

**Comment by rwhitley7** [comment]
Hello @hlwang1124 and @mei123hao. I am also interested in the code for the depth map generation. Can one of you kindly email it to me also? muntaner@msu.edu. 

Thanks

**Comment by hlwang1124** [comment]
@DaniloXiao Can you provide your email for me?
@rwhitley7 I have sent the code to your email.

**Comment by rwhitley7** [comment]
Got it. Thank you so much

**Comment by DaniloXiao** [comment]
> @DaniloXiao Can you provide your email for me?
> @rwhitley7 I have sent the code to your email.
My email daniloxiao@gmail.com，I appreciate your help.

**Comment by hlwang1124** [comment]
@DaniloXiao Got it!

**Comment by xujinjiang** [comment]
hello! Can you share the script generously? thanks!
My email:  xujinjiang_cv@163.com

**Comment by USTCLH** [comment]
Hi, @hlwang1124 . I also want the script. Can you share it with me? Thanks!
My email: li_heng@mail.ustc.edu.cn

**Comment by rock19970106** [comment]
Hi, @hlwang1124 . I also want the script. Can you share it with me? Thanks!
My email: zhlupeng@mail.ustc.edu.cn

**Comment by ZZZENG** [comment]
Hello, @hlwang1124 So sorry to bother you, can you share it with me? Thank you very much~
This is my Email: zeng.yuan.yi@foxmail.com

**Comment by pridy999** [comment]
Hi, @hlwang1124 Could you please share the script with me? I also want to learn about it. Thank you very much!
My email: ZH0027AO@e.ntu.edu.sg

**Comment by TamasIll** [comment]
Hi @hlwang1124, I'm interested in the script, too. Could you please share with me? Thanks a lot!
E-mail: illes.tamas@itqs.hu

**Comment by TonyX19** [comment]
> > Hi, @mei123hao . So sorry for the late response. I have sent the code to your email. Thanks for your understanding.
> 
> Thank you very much!

Hi, could share the script with me? Thank you 44480069@qq.com

**Comment by phamngocninh** [comment]
@mei123hao  I'm interested in the script, too. Could you please share with me? Thanks you!
Email: phamngocninh.bk@gmail.com

**Comment by BEOMSEOK-K** [comment]
I'm working on a road estimation project. So I'm interested in the script, too. Could you please share with me? Thanks you!
Email: qjatjr4479@gmail.com

**Comment by MaryAhn** [comment]
Hello @hlwang1124 , I'm also interested in the script since our research aim generating depth image based on your model SNE-RoadSeg. Would you share the script for generating depth image? Thanks in advance.
Email: khahn196@gmail.com

**Comment by HereQ** [comment]
Hi, @hlwang1124 Could you please share the script with me? I also want to learn about it. Thank you very much!
Email: quyu1023@gmail.com

**Comment by Ahmad-Abu-Alqumsan** [comment]
Is it possible to share the code with me as well, my email is engahmad101@gmail.com
It would be highly appreciated,

**Comment by yhl1010** [comment]
> Hi, @mei123hao . I will organize the code and send it to you.

hi，Could you please share the code how to generate dense depth images from lidar point cloud with me? thanks!Email:917826885@qq.com

**Comment by ChouTatsukyo** [comment]
@TonyX19 @hlwang1124 Hello, I am also doing research in this field recently, and I want to make my own dataset by kitti dataset, but I cannot achieve the reproduction of depth map, could you please send me the relevant code? My email is jxnu_chenyue@126.com. Thank you very much!

**Comment by prograguo** [comment]
I also want the script. Can you share it with me? Thanks!
1348234045@qq.com
