### ISSUE TITLE
Questions regarding the evaluation

### ISSUE THREAD

**Issue by zeng32** [hlwang1124/SNE-RoadSeg#3]
1. Would you please share your evaluation code(devkit_road) with us? 
the original code downloaded from the http://www.cvlibs.net/datasets/kitti/eval_road.php uses very old dependencies: python 2.7/numpy 1.51/opencv 2.4.6. It is almost impossible to rebuild this kind of environment. 
Do you also use the original code? if not, would you please share your new code with us?

2. The evaluation method which you are using in the training process is different from the evaluation code in the devkit_road, right?
Therefore, the evaluation result showing in the training process can only be regarded as an indicator and can not be used as the result for submission to the server, am I correct?

Thanks in advance!

**Comment by hlwang1124** [comment]
Yes. We do not use the evaluation method in KITTI Road, and we submit our results in the testing set to the server for KITTI evaluation results.

**Comment by zeng32** [comment]
Thanks very much for the quick reply!
For submission, I believe the results must be transferred into the Birds Eye View (BEV), right?
However, I can not locate the perspective-to-BEV code in your test.py source code.
Could you please share more info. on how and what do you submit to the KITTI server?
Much appreciated!!

**Comment by hlwang1124** [comment]
KITTI has provided the transformation code (``Download development kit`` in this [page](http://www.cvlibs.net/datasets/kitti/eval_road.php)). You can simply run the ``transform2BEV.py`` for the perspective transformation.

**Comment by zeng32** [comment]
Thanks a lot!
The last question, I notice that the best model you choose is the one with the best F-score, does this F score in your training process comply with the F score reported by KITTI server after your submission?

**Comment by hlwang1124** [comment]
It's not. KITTI adopts Max-Fscore. Specifically, it will find the best threshold for the road segmentation and compute the corresponding F-score. Differently, we use a constant threshold.
Actually, we adopt F-score as the primary indicator for model selection because it combines both precision and recall. You can also use iou or other similar metrics. According to our experience, the trend of the commonly used F-score that we use is similar to that of the Max-Fscore that KITTI adopts.

**Comment by zeng32** [comment]
Thanks for your excellent work and for being patient with me!
