### ISSUE TITLE
The problem of the R2D dataset

### ISSUE THREAD

**Issue by lrjing** [hlwang1124/SNE-RoadSeg#31]
Hello!
I downloaded the R2D dataset you published before, and I want to use it further.  Where can I get more information about this dataset?  For example, what category does the label of the dataset correspond to, some corresponding settings, and so on.  
Thank you very much!!!

**Comment by hlwang1124** [comment]
Hi, @lrjing . As mentioned in the dataset README, the dataset is collected in the CARLA simulation environment. The label information can be founded [here](https://carla.readthedocs.io/en/latest/ref_sensors/#semantic-segmentation-camera). You can refer to the dataset README and the CARLA tutorial for more information.

**Comment by lrjing** [comment]
Thank you very much for your answer! 
 I have been unable to download the dataset from your website link before, or the download was interrupted.  So I used the dataset that my friend downloaded before, but I didn't see the README. Therefore, I couldn't get more information about the dataset. Your answer helps me a lot.Thanks again!
 I would also like to ask whether the download link can be downloaded normally?  I tried many times but failed. @hlwang1124

**Comment by hlwang1124** [comment]
Sorry for the inconvenience. The dataset can be downloaded from [Google Drive](https://drive.google.com/file/d/1IKn3WS9kLXhbVTO-47C06ZroPwEVP5AG/view?usp=sharing) or [our Lab NAS](http://gofile.me/4jm56/VtuuSvYP5). Grateful if you could tell me where the invalid download link is, and I will update them.

**Comment by lrjing** [comment]
Thank you very much!!

**Comment by lrjing** [comment]
@hlwang1124 Excuse me. Is the depth map in the R2D dataset a normal vector map converted by the SNE module? Because I feel different from the common depth map.
   If I want to get the true depth, do I use a formula in README to get it?Thank you!!

**Comment by hlwang1124** [comment]
Hi, @lrjing . Our R2D dataset is collected in the Carla simulation environment. Please refer to this [link](https://carla.readthedocs.io/en/stable/cameras_and_sensors/) for the data format of depth maps and semantic segmentation maps.

**Comment by lrjing** [comment]
@hlwang1124  Thank you !!!
