### ISSUE TITLE
calibration file of R2D dataset

### ISSUE THREAD

**Issue by MaryAhn** [hlwang1124/SNE-RoadSeg#46]
Hi. I would like to train this model on R2D dataset. However, I could not find information of calibration file even if I refer to carla homepage and searched 'calibration'/ I would like to know how to get calibration files of R2D dataset. 

Thanks in advance.

**Comment by hlwang1124** [comment]
Hi, @MaryAhn . The calibration files of R2D dataset is in the [dataset zip file](https://drive.google.com/file/d/1IKn3WS9kLXhbVTO-47C06ZroPwEVP5AG/view?usp=sharing).

**Comment by MaryAhn** [comment]
> Hi, @MaryAhn . The calibration files of R2D dataset is in the [dataset zip file](https://drive.google.com/file/d/1IKn3WS9kLXhbVTO-47C06ZroPwEVP5AG/view?usp=sharing).

You mean intrinsic matrix in readme file?

**Comment by hlwang1124** [comment]
Yes.
