### ISSUE TITLE
how to convert depth image in R2D

### ISSUE THREAD

**Issue by BEOMSEOK-K** [hlwang1124/SNE-RoadSeg#48]
I'm working on a road estimation project for self-studying. I'm trying to convert the depth image in R2D, but although I use the converted depth image when I run the run_example code, the accuracy was bad. So I'm interested in the script which is described for the conversion method too. Could you please share with me? Thanks you!
Email : qjatjr4479@gmail.com

**Comment by hlwang1124** [comment]
I have sent an email to you.
