### ISSUE TITLE
Can this algorithm be used for document image layout segmentation？

### ISSUE THREAD

**Issue by hande6688** [hlwang1124/SNE-RoadSeg#5]

**Comment by hlwang1124** [comment]
Sorry that I am not familiar with this task. Considering that our network is designed for taking two different modalities of data as input, I think you can try our approach if your task also has such demand.

**Comment by hande6688** [comment]
It's dividing the document into columns,
The column effect is as follows: red on the left represents label 1, and yellow on the right represents label 2：
![image](https://user-images.githubusercontent.com/29244715/92296517-19666680-ef68-11ea-9bca-d1eb99e7bc3f.png)

**Comment by hlwang1124** [comment]
According to your description, I think it is more related to an object detection problem than a semantic segmentation problem.

**Comment by hande6688** [comment]
正在使用发音


The shape of the layout is irregular, and the semantic segmentation is closer










------------------ Original ------------------

**Comment by hlwang1124** [comment]
I think you can try existing instance segmentation approaches such as Mask-RCNN, because it is more appropriate to divide different columns with different ids than different labels.
