### ISSUE TITLE
How can we generate the dense depth image from sparse LiDAR points?

### ISSUE THREAD

**Issue by ZhenboSong** [hlwang1124/SNE-RoadSeg#7]
Hi Hengli,
Could you provide some instructions for generating dense depth maps? Using depth completion networks or simply using interpolation? If we don't have perfect depth maps, could SNE and RoadSeg Net generalize well?

**Comment by hlwang1124** [comment]
Hi Zhenbo. In our experiments, we simply use interpolation.
In addition, we have not tested our approach under different noise levels. However, I think our approach can generalize well on the commonly used sensors, such as LiDAR for self-driving cars and RealSense for mobile robots.

**Comment by ZhenboSong** [comment]
Thanks, Hengli. Could you provide the code for interpolation? We have tried several depth completion methods, but RoadSeg results are not good as you provided in your videos.

**Comment by hlwang1124** [comment]
Hi, Zhenbo. Actually, the code we use is very simple, `griddata` method in Matlab, which is also equivalent to `scipy.interpolate.griddata` in python. We have provided the dense depth maps in the KITTI Road Dataset, and you can also have a look.

**Comment by ZhenboSong** [comment]
Great! Thanks again.

**Comment by cattpku** [comment]
Hi @ZhenboSong, have you successfully generated the uint16 depth image from lidar data? If so, can you kindly share the script? Thanks.
