### ISSUE TITLE
How to elevate the training results?

### ISSUE THREAD

**Issue by zeng32** [hlwang1124/SNE-RoadSeg#9]
After training with the default hyperparameters, my evaluation result from kitti server is not as good as in your report:
                  MaxF
UM_Road: 95.12%
UMM_Road: 97.05%
UU_Road : 94.39%
urban_road: 95.76%

Could you please give me any suggestions to improve the performance?
Thanks in advance.

**Comment by hlwang1124** [comment]
Hi, zeng. Sorry for the late response. You can try to use some data augmentation techniques.

**Comment by zeng32** [comment]
Thank you for the advice!

**Comment by hlwang1124** [comment]
Yes, I think this performance degradation is due to overfitting.

It is right, since there is no lidar data in the upper half area. It does not matter, because the empty area only contains sky, tall trees and buildings.

**Comment by zeng32** [comment]
Thanks for your kind reply!
